### ISSUE TITLE
Improve demand allocation accuracy

### ISSUE THREAD

**Issue by yashkumar1803** [catalyst-cooperative/electricity-demand-mapping#3]
**Identify systematic biases and improve the demand allocation model** 

Right now the parameters conform to the normalized population mapping matrix. This shows good prediction accuracy at the national level but there is state-level-bias which needs to be addressed.

**Develop functions to create weights which adjust the demand allocation parameters:** Presently, the parameter values are defined by the average population within the intersection of a demand area and census tract. The actual demand could possibly be skewed by the difference in types of energy uses e.g. residential, commercial, transportation energy.

**Develop a testing methodology to check the accuracy of the new weights:** The new weights will be created to handle the systematic biases and then the modified values will be validated using a training and testing methodology.

**Comment by cmgosnell** [comment]
stale
