### ISSUE TITLE
Proposed processing pipeline

### ISSUE THREAD

**Issue by ezwelty** [catalyst-cooperative/electricity-demand-mapping#6]
Here is a general and modular approach I came up with during my meetings with @zaneselvans and @yashkumar1803 today.

## Input layers

A `layer` contains many `features`, each of which have an associated `geometry` and many `attributes`. For our purposes, let's allow each attribute to be one of two types:

  - `constant`: The attribute is equal everywhere within the feature geometry (e.g. identifier, percent area).
    - When splitting a feature, the attribute value for the resulting features is that of their parent: e.g. `[1] -> [1], [1]`.
    - When joining features, the attribute value for the resulting feature must be a function of its children: e.g. `[1], [1] -> [1, 1]` (list) or `1` (appropriate aggregation function, e.g. median or area-weighted mean).
  - `uniform`: The attribute is uniformly distributed within the feature geometry (e.g. count, area).
    - When splitting a feature, the attribute value for the resulting features is proportional to their area: e.g. `[1]` (100% area) `-> [0.4]` (40% area), `[0.6]` (60% area).
    - When joining features, the attribute value for the resulting feature is the sum of its children: e.g. `[0.4], [0.6] -> [1]`.

For example, say we have a regional `demand` layer:

| geometry | demand_id | total_demand |
| -- | -- | -- |
|  | *constant* | *constant* |
| POLYGON *A* | 1 | 10 |
| POLYGON *B* | 2 | 5 |

where *A* and *B* overlap, and a local `population` layer:

| geometry | population_id | population |
| -- | -- | -- |
|  | *constant* | *uniform* |
| POLYGON *a* | 1 | 100 |
| POLYGON *b* | 2 | 100 |

where polygons *a* and *b* do not overlap, *a* is within *A*, and *b* is 60% in *A* and 40% in the intersection of *A* and *B*.

## Flatten layers

```python
def flatten(layers, attributes):
  """
  Arguments:
    layers (list of GeoDataFrames): Polygon feature layers.
    attributes (dict): Attribute names and types ({ name: type, ... }),
      where type is either 'constant' or 'uniform'.
  Returns:
    GeoDataFrame: Polygon feature layer with all attributes named in `attributes`.
  """
```

We can merge our many polygon layers into a single layer with maximum granularity by splitting all features (across all layers) on all feature boundaries and recalculating attributes following the rules above.

1. Split each layer on the boundaries of its own features. For `demand`, this gives rise to two features where *A* and *B* intersect (with polygon *A∩B*, each with the attributes of *A* and *B*, respectively) and features for the difference of *A* and *B* (with polygons *A\\B* and *B\\A*, respectively):

| geometry | demand_id | total_demand |
| -- | -- | -- |
|  | *constant* | *constant* |
| POLYGON *A∩B* | 1 | 10 |
| POLYGON *A∩B* | 2 | 5 |
| POLYGON *A\\B* | 1 | 10 |
| POLYGON *B\\A* | 2 | 5 |

2. Starting with one of these pre-split layers, recursively split on the features of each of the remaining pre-split layers, and merge overlapping features across layers. For `population`, this means that *b* is split 60% by *A\\B* (resulting in *b∩A\\B*) and 40% by each *A∩B* (resulting in two *b∩A∩B*).

| geometry | demand_id | total_demand | population_id | population |
| -- | -- | -- | -- | -- |
|  | *constant* | *constant* | *constant* | *uniform*
| POLYGON *a* | 1 | 10 | 1 | 100
| POLYGON *b∩A\\B* | 1 | 10 | 2 | 60
| POLYGON *b∩A∩B* | 1 | 10 | 2 | 40
| POLYGON *b∩A∩B* | 2 | 5 | 2 | 40

... *ignoring the remaining polygons with no population*

## Predict demand

```python
def predict(layer):
  """
  Arguments:
    layer (GeoDataFrame): Polygon feature layer.
  Returns:
    numpy.ndarray: Hourly demand timeseries for each `layer` feature.
  """
```

Having flattened all attributes into a single granular feature layer, we can now proceed to predict demand for each feature. For example, we could divide each `population` by the sum of `population` grouped by `demand_id` and use that fraction to scale the demand timeseries associated with each `demand_id`. Or any other calculation...

## Aggregate layer

```python
def aggregate(layer, polygons, attributes):
  """
  Arguments:
    layer (GeoDataFrame): Polygon feature layer.
    polygons: Polygon geometries to aggregate into.
    attributes: Same as for flatten().
  Returns:
    GeoDataFrame: Polygon feature layer with geometries from `polygons`
      and all attributes named in `attributes`.
  """
```

Optionally, the granular features could be aggregated first and prediction performed on these aggregated features. First, all `layer` features are split at `polygons` boundaries, then all split features within each polygon are joined together, as always following the attribute rules described above. In practice, there would need to be a way to specify aggregation functions for `constant` attributes, or let `aggregate()` just split and assign features to the target polygons, but leave the `DataFrame.groupby` logic to the user.

**Comment by yashkumar1803** [comment]
In the example, is `total_demand` a `constant` or a `uniform` attribute? Isn't `total_demand` also disaggregating at the smallest unit level? Or am I getting it wrong?

**Comment by ezwelty** [comment]
In the example, it is treated as a `constant` so that it propagates unchanged in the disaggregation step. Since it is the attribute you are modeling, no sense in assuming it is spatially uniformly distributed!

**Comment by yashkumar1803** [comment]
OK, I understood. Thanks!
