### ISSUE TITLE
Incorporate New Datasets to Improve Demand Allocation from First Principles

### ISSUE THREAD

**Issue by yashkumar1803** [catalyst-cooperative/electricity-demand-mapping#8]
# Add more datasets which can be used to better allocate demand from first principles

Datasets to consider
1. NREL mining, agro datasets
2. Other attributes from the census i.e. (income levels etc.)
3. CBECS microdata (https://www.eia.gov/consumption/commercial/data/2012/index.php?view=microdata)
4. RECS microdata (https://www.eia.gov/consumption/residential/data/2015/index.php?view=microdata)
5. Temperature data (NOAA Climate Data)
6. NATCARB (edx.netl.doe,gov)

**Comment by cmgosnell** [comment]
moving this over into the main pudl repo
